use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/linyanzuo/MoeRepo.git'

target 'MoeUI_Example' do
  pod 'SnapKit', '~> 5.0.0'
  pod 'MoeUI', :path => '../'

  target 'MoeUI_Tests' do
    inherit! :search_paths
    
  end
end
